/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FavoritesImport } from './routes/favorites'
import { Route as BookIdImport } from './routes/book.$id'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const FavoritesRoute = FavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/favorites.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BookIdRoute = BookIdImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/book.$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/favorites': typeof FavoritesRoute
  '/settings': typeof SettingsLazyRoute
  '/book/$id': typeof BookIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/favorites': typeof FavoritesRoute
  '/settings': typeof SettingsLazyRoute
  '/book/$id': typeof BookIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/favorites': typeof FavoritesRoute
  '/settings': typeof SettingsLazyRoute
  '/book/$id': typeof BookIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/settings' | '/book/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/settings' | '/book/$id'
  id: '__root__' | '/' | '/favorites' | '/settings' | '/book/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FavoritesRoute: typeof FavoritesRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  BookIdRoute: typeof BookIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FavoritesRoute: FavoritesRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  BookIdRoute: BookIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorites",
        "/settings",
        "/book/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/favorites": {
      "filePath": "favorites.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/book/$id": {
      "filePath": "book.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
